#!/usr/bin/env python3
"""Run the preregistered order-adjusted repeated-measures ANCOVA candidate.

INTERNAL CANDIDATE ONLY. This script reads the authoritative OSF master dataset
but refuses to write into that repository. Its output must be reviewed, adopted,
and regenerated by the OSF package maintainer before manuscript use.

The registered omnibus condition test is implemented as a partial F test that
compares these nested ordinary least-squares models on complete within-subject
triplets:

    reduced: value ~ participant + numeric block position
    full:    value ~ participant + numeric block position + condition

Participant fixed effects provide the repeated-measures blocking. The two added
condition indicators test the three-level within-subject condition effect after
adjustment for the block position at which each condition was presented.
"""

from __future__ import annotations

import argparse
import hashlib
import platform
import re
import sys
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
import scipy
from scipy import stats


CONDITIONS = (
    ("dark_screen_control", "black_screen_control", "block_of_black_screen_control"),
    ("symmetric_coupling", "symmetric_coupling", "block_of_symmetric_coupling"),
    ("asymmetric_coupling", "asymmetric_coupling", "block_of_asymmetric_coupling"),
)


@dataclass(frozen=True)
class OutcomeSpec:
    family: str
    dv: str
    outcome_label: str
    prefix: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--package-root", required=True, help="Authoritative OSF repository root.")
    parser.add_argument("--output-dir", default="", help="Internal for-ai output directory.")
    parser.add_argument("--write", action="store_true", help="Write internal candidate outputs.")
    return parser.parse_args()


def is_within(child: Path, parent: Path) -> bool:
    try:
        child.resolve().relative_to(parent.resolve())
        return True
    except ValueError:
        return False


def included_mask(series: pd.Series) -> pd.Series:
    if pd.api.types.is_bool_dtype(series.dtype):
        return series.fillna(False)
    return series.astype(str).str.strip().str.lower().isin({"true", "t", "1", "yes", "y"})


def letter_to_ordinal(value: object) -> float:
    if pd.isna(value):
        return np.nan
    text = str(value).strip()
    if not text:
        return np.nan
    try:
        return float(text)
    except ValueError:
        first = text[0].upper()
        return float(ord(first) - ord("A") + 1) if "A" <= first <= "Z" else np.nan


def make_specs() -> list[OutcomeSpec]:
    specs = [OutcomeSpec("PLV", "PLV", "PLV", "plv")]
    asc_labels = {
        "EU": "Experience of Unity",
        "SE": "Spiritual Experience",
        "BS": "Blissful State",
        "IS": "Insightfulness",
        "DIS": "Disembodiment",
        "ICC": "Impaired Control and Cognition",
        "ANX": "Anxiety",
        "CI": "Complex Imagery",
        "EI": "Elementary Imagery",
        "AVS": "Audio-Visual Synesthesia",
        "CMP": "Changed Meaning of Percepts",
    }
    for code, label in asc_labels.items():
        specs.append(OutcomeSpec("ASC", f"asc_avg_{code}", label, f"asc_avg_{code}"))
    for code, label in {
        "POSE": "Positive Effects",
        "DISE": "Distressing Effects",
        "PERE": "Perceptual Effects",
    }.items():
        specs.append(OutcomeSpec("ASC3", f"asc3_avg_{code}", label, f"asc3_avg_{code}"))
    for prefix, label in {
        "self_perceived_body_boundaries_scale": "Perceived body boundaries",
        "self_spatial_frame_of_reference_continuum": "Spatial frame of reference",
        "self_small_self_scale": "Small Self",
    }.items():
        specs.append(OutcomeSpec("self", prefix, label, prefix))
    for statistic in ("peak", "auc"):
        for code, label in asc_labels.items():
            prefix = f"tracer_{statistic}_{code}"
            specs.append(OutcomeSpec(f"tracer_{statistic}", prefix, label, prefix))
    return specs


def make_long(data: pd.DataFrame, spec: OutcomeSpec) -> pd.DataFrame:
    pieces: list[pd.DataFrame] = []
    required = {"participant_id"}
    for condition, value_suffix, order_col in CONDITIONS:
        value_col = f"{spec.prefix}_{value_suffix}"
        required.update((value_col, order_col))
        if value_col not in data.columns or order_col not in data.columns:
            continue
        pieces.append(
            pd.DataFrame(
                {
                    "participant_id": data["participant_id"].astype(str),
                    "condition": condition,
                    "block_position": pd.to_numeric(data[order_col], errors="coerce"),
                    "value": (
                        data[value_col].map(letter_to_ordinal)
                        if spec.family == "self"
                        else pd.to_numeric(data[value_col], errors="coerce")
                    ),
                }
            )
        )
    missing = sorted(required.difference(data.columns))
    if missing:
        raise KeyError(f"Missing columns for {spec.dv}: {', '.join(missing)}")
    long = pd.concat(pieces, ignore_index=True).dropna(subset=["block_position", "value"])
    complete_ids = long.groupby("participant_id", sort=False).size()
    complete_ids = complete_ids.index[complete_ids.eq(3)]
    return long[long["participant_id"].isin(complete_ids)].copy()


def design_matrices(long: pd.DataFrame) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    participant = pd.get_dummies(long["participant_id"], drop_first=True, dtype=float)
    condition = pd.get_dummies(long["condition"], drop_first=True, dtype=float)
    intercept = np.ones((len(long), 1), dtype=float)
    block = long[["block_position"]].to_numpy(dtype=float)
    reduced = np.column_stack((intercept, participant.to_numpy(dtype=float), block))
    full = np.column_stack((reduced, condition.to_numpy(dtype=float)))
    return long["value"].to_numpy(dtype=float), reduced, full


def residual_sse(y: np.ndarray, design: np.ndarray) -> tuple[float, int]:
    coefficients, _, rank, _ = np.linalg.lstsq(design, y, rcond=None)
    residuals = y - design @ coefficients
    return float(residuals @ residuals), int(rank)


def run_outcome(data: pd.DataFrame, spec: OutcomeSpec) -> dict[str, object]:
    long = make_long(data, spec)
    y, reduced, full = design_matrices(long)
    sse_reduced, rank_reduced = residual_sse(y, reduced)
    sse_full, rank_full = residual_sse(y, full)
    df_num = rank_full - rank_reduced
    df_den = len(y) - rank_full
    if df_num != 2 or df_den <= 0:
        raise RuntimeError(f"Unexpected model degrees of freedom for {spec.dv}: {df_num}, {df_den}")
    effect_ss = max(0.0, sse_reduced - sse_full)
    f_value = (effect_ss / df_num) / (sse_full / df_den)
    p_value = float(stats.f.sf(f_value, df_num, df_den))
    partial_eta2 = effect_ss / (effect_ss + sse_full)
    return {
        "family": spec.family,
        "dv": spec.dv,
        "outcome_label": spec.outcome_label,
        "n_complete": int(long["participant_id"].nunique()),
        "estimand": "partial F for condition adjusted for numeric block position with participant blocking",
        "f_condition": float(f_value),
        "df_num": int(df_num),
        "df_den": int(df_den),
        "p_condition": p_value,
        "partial_eta2": float(partial_eta2),
        "sse_reduced": float(sse_reduced),
        "sse_full": float(sse_full),
        "rank_reduced": int(rank_reduced),
        "rank_full": int(rank_full),
    }


def bh_adjust(values: pd.Series) -> np.ndarray:
    p = values.to_numpy(dtype=float)
    order = np.argsort(p)
    ranked = p[order]
    adjusted = ranked * len(ranked) / np.arange(1, len(ranked) + 1)
    adjusted = np.minimum.accumulate(adjusted[::-1])[::-1]
    adjusted = np.minimum(adjusted, 1.0)
    result = np.empty_like(adjusted)
    result[order] = adjusted
    return result


def compare_with_current_pipeline(package_root: Path, candidate: pd.DataFrame) -> pd.DataFrame:
    current_csv = package_root / "3.Results" / "2.PrimaryStatistics" / "04_primary_family_summary.csv"
    current = pd.read_csv(current_csv)[
        [
            "dv",
            "chi2_condition_mixed",
            "p_condition_mixed",
            "q_condition_mixed",
            "f_condition_rm_anova",
            "p_condition_rm_anova",
        ]
    ].copy()
    plv_report = (
        package_root / "3.Results" / "2.PrimaryStatistics" / "01_primary_statistical_results.txt"
    ).read_text(encoding="utf-8")
    plv_match = re.search(
        r"Mixed model LRT \(condition \+ order vs order\) \| "
        r"chi2=([0-9.eE+-]+), df=([0-9]+), p=([0-9.eE+-]+)",
        plv_report,
    )
    if not plv_match:
        raise RuntimeError("Could not parse the current PLV mixed-model comparison")
    current = pd.concat(
        (
            current,
            pd.DataFrame(
                {
                    "dv": ["PLV"],
                    "chi2_condition_mixed": [float(plv_match.group(1))],
                    "p_condition_mixed": [float(plv_match.group(3))],
                    "q_condition_mixed": [float(plv_match.group(3))],
                    "f_condition_rm_anova": [np.nan],
                    "p_condition_rm_anova": [np.nan],
                }
            ),
        ),
        ignore_index=True,
    )
    keep = [
        "family",
        "dv",
        "outcome_label",
        "n_complete",
        "f_condition",
        "df_num",
        "df_den",
        "p_condition",
        "q_condition_bh",
        "partial_eta2",
    ]
    comparison = candidate[keep].merge(current, on="dv", how="left", validate="one_to_one")
    if comparison["p_condition_mixed"].isna().any():
        missing = comparison.loc[comparison["p_condition_mixed"].isna(), "dv"].tolist()
        raise RuntimeError(f"Current-pipeline comparison is missing: {missing}")
    comparison["candidate_nominal_significant"] = comparison["p_condition"].lt(0.05)
    comparison["current_mixed_nominal_significant"] = comparison["p_condition_mixed"].lt(0.05)
    comparison["nominal_decision_unchanged"] = comparison[
        "candidate_nominal_significant"
    ].eq(comparison["current_mixed_nominal_significant"])
    comparison["candidate_fdr_significant"] = comparison["q_condition_bh"].lt(0.05)
    comparison["current_mixed_fdr_significant"] = comparison["q_condition_mixed"].lt(0.05)
    comparison["fdr_decision_unchanged"] = comparison["candidate_fdr_significant"].eq(
        comparison["current_mixed_fdr_significant"]
    )
    comparison["interpretation_unchanged_at_both_thresholds"] = comparison[
        "nominal_decision_unchanged"
    ] & comparison["fdr_decision_unchanged"]
    return comparison


def main() -> int:
    args = parse_args()
    script_path = Path(__file__).resolve()
    manuscript_root = script_path.parents[2]
    for_ai_root = manuscript_root / "for-ai"
    package_root = Path(args.package_root).expanduser().resolve()
    if package_root.name != "0_OSF_reproducability_package":
        raise ValueError("--package-root must be the repository named 0_OSF_reproducability_package")
    output_dir = (
        Path(args.output_dir).expanduser().resolve()
        if args.output_dir
        else for_ai_root / "statistical-audit" / "candidate-registered-results"
    )
    if is_within(output_dir, package_root):
        raise ValueError("Refusing to write candidate output inside the authoritative OSF repository")
    if not is_within(output_dir, for_ai_root):
        raise ValueError("Candidate output must remain inside this manuscript repository's for-ai directory")

    master_csv = package_root / "3.Results" / "1.MasterDataset" / "01_master_analysis_dataset.csv"
    data_all = pd.read_csv(master_csv)
    if "include_in_analyses" not in data_all.columns:
        raise KeyError("Missing include_in_analyses column")
    data = data_all.loc[included_mask(data_all["include_in_analyses"])].copy()
    if len(data) != 39 or data["participant_id"].nunique() != 39:
        raise RuntimeError("The candidate pipeline requires the locked final included sample of N=39")

    results = pd.DataFrame(run_outcome(data, spec) for spec in make_specs())
    results["q_condition_bh"] = np.nan
    for family, indexes in results.groupby("family", sort=False).groups.items():
        if family == "PLV":
            results.loc[indexes, "q_condition_bh"] = results.loc[indexes, "p_condition"]
        else:
            results.loc[indexes, "q_condition_bh"] = bh_adjust(results.loc[indexes, "p_condition"])
    comparison = compare_with_current_pipeline(package_root, results)

    display_columns = [
        "family",
        "dv",
        "n_complete",
        "f_condition",
        "df_num",
        "df_den",
        "p_condition",
        "q_condition_bh",
        "partial_eta2",
    ]
    print(results[display_columns].to_string(index=False))
    if not args.write:
        print("\nDry run only. Re-run with --write to save internal candidate output under for-ai/.")
        return 0

    output_dir.mkdir(parents=True, exist_ok=True)
    output_csv = output_dir / "candidate_registered_rm_ancova.csv"
    results.to_csv(output_csv, index=False, lineterminator="\n")
    comparison_csv = output_dir / "candidate_vs_current_omnibus_interpretation.csv"
    comparison.to_csv(comparison_csv, index=False, lineterminator="\n")
    digest = hashlib.sha256(master_csv.read_bytes()).hexdigest()
    (output_dir / "ADOPTION_REQUIRED.txt").write_text(
        "\n".join(
            (
                "INTERNAL CANDIDATE OUTPUT ONLY",
                "These files are not authoritative and must not be cited or submitted.",
                "The implementation must be adopted, reviewed, and regenerated in:",
                "https://github.com/GeorgeFejer91/0_OSF_reproducability_package",
                f"Authoritative input: {master_csv}",
                f"Input SHA-256: {digest}",
                f"Included N: {len(data)}",
                "Registered model: participant blocking + numeric block position + three-level condition",
                "Current-vs-candidate nominal decisions unchanged: "
                f"{int(comparison['nominal_decision_unchanged'].sum())}/{len(comparison)}",
                "Current-vs-candidate FDR decisions unchanged: "
                f"{int(comparison['fdr_decision_unchanged'].sum())}/{len(comparison)}",
                "Windows R/BayesFactor remains unavailable; the joint ordered Bayes test is still pending.",
                "",
            )
        ),
        encoding="utf-8",
        newline="\n",
    )
    (output_dir / "candidate_python_session.txt").write_text(
        "\n".join(
            (
                f"Python: {sys.version}",
                f"Platform: {platform.platform()}",
                f"NumPy: {np.__version__}",
                f"pandas: {pd.__version__}",
                f"SciPy: {scipy.__version__}",
                "",
            )
        ),
        encoding="utf-8",
        newline="\n",
    )
    print(f"\nWrote internal candidate output to: {output_csv}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
